msg:
  badge: '&6[Treebo Teleport]&r '
  error: '&4ERROR:&r '
  badCommand: '$4Incorrect usage:$r '
  addkey: '%badge%You have received %amount% %type% keys.'

bstatsIntegration: true

categories:
  common: 'common.yml'
  rare: 'rare.yml'
  legendary: 'legendary.yml'
  mythic: 'mythic.yml'

gui:
  headDataMatch: '1d060f05-7253-4959-b583-4e023332c965'
  # eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vZWR1Y2F0aW9uLm1pbmVjcmFmdC5uZXQvd3AtY29udGVudC91cGxvYWRzL1RyZWVib0NoZXN0X3doaXRlX3NoYWRvd2VkcGRuLnBuZyJ9fX0=
  rows: 3
  title: '&3&l[&3Treebo Treasures&3&l]&r'
  countLore: '.&a You have -* &6{keyCount} *- &c&l&n{keyType}&a Keys remaining'
  filler: LIGHT_BLUE_STAINED_GLASS_PANE
  items:
    common:
      material: IRON_BLOCK
      position: 11
      title: '&f&lCommon &rKey'
    uncommon:
      material: GOLD_BLOCK
      position: 12
      title: '&e&lUncommon &rKey'
    legendary:
      material: DIAMOND_BLOCK
      position: 13
      title: '&b&lLegendary &rKey'
    epic:
      material: PURPUR_BLOCK
      position: 14
      title: '&5&lEpic &rKey'

#Events will change the loot table in their given month.
events:
  1:
    name: ''
  2:
    name: ''
  3:
    name: ''
  4:
    name: 'easter'
  5:
    name: ''
  6:
    name: ''
  7:
    name: ''
  8:
    name: ''
  9:
    name: ''
  10:
    name: 'halloween'
  11:
    name: ''
  12:
    name: 'christmas'

doDailyRewards: false
